### ISSUE TITLE
Xây dựng tài liệu đặc tả phần mềm + viết plan test

### ISSUE THREAD

**Issue by bngoc1307** [bngoc1307/Nhom04_CCPTPM#14]
- [ ] Task 1: Tổng hợp và chỉnh sửa usercase 
- [ ] Task 2: Tổng hợp và chỉnh sửa class diagram
- [ ] Task 3: Tổng hợp và chỉnh sửa activity diagram
- [ ] Task 4: Tổng hợp lại các usercase, class diagram, activity diagram và xây dựng tài liệu đặc tả phần mềm hoàn chỉnh
- [ ] Task 5: Viết plan test cho chức năng create project
- [ ] Task 6: Viết plan test cho chức năng list all project
- [ ] Task 7: Tổng hợp và xem xét chỉnh sửa các plan test cho hoàn chỉnh

**Comment by huypq20110653** [comment]
# Task 1: Tổng hợp và chỉnh sửa Usecase
Link file tổng hợp Usecase của project: https://docs.google.com/document/d/1t3TE_ksJfEdRqArvJm0DR3wCBaTL1vk-qtQDEhaDN_c/edit?usp=sharing

**Comment by huypq20110653** [comment]
# Task 2: Tổng hợp và chỉnh sửa class diagram
## Class diagram cho module videoserver.apps.projects
```mermaid
classDiagram
    class FlaskMethodView {
        + get()
        + post()
        + put()
        + delete()
        + patch()
        + __init__()
    }

    FlaskMethodView <|-- MethodView
    class MethodView {
        + __init__()
        + dispatch_request()
        + project
    }

    MethodView <|-- ListUploadProject
    class ListUploadProject {
        + post()
        + get()
    }

    MethodView <|-- RetrieveEditDestroyProject
    class RetrieveEditDestroyProject {
        + schema_edit
        + get()
        + put()
        + delete()
    }

    MethodView <|-- DuplicateProject
    class DuplicateProject {
        + post()
    }

    MethodView <|-- RetrieveOrCreateThumbnails
    class RetrieveOrCreateThumbnails {
        + schema_thumbnails
        + post()
        + get()
        + _get_timeline_thumbnails()
        + _get_preview_thumbnail()
    }

    MethodView <|-- GetRawVideo
    class GetRawVideo {
        + get()
    }

    MethodView <|-- GetRawPreviewThumbnail
    class GetRawPreviewThumbnail {
        + get()
    }

    MethodView <|-- GetRawTimelineThumbnail
    class GetRawTimelineThumbnail {
        + get()
    }
```

## Class diagram cho module videoserver.apps.lib.storage

```mermaid
classDiagram
    class MediaStorageInterface {
        + get()
        + put()
        + replace()
        + get_range()
        + delete()
        + delete_dir()
    }

    MediaStorageInterface <|-- FileSystemStorage
    class FileSystemStorage {
        + get()
        + get_range()
        + put()
        + replace()
        + delete()
        + delete_dir()
    }
```

## Class diagram cho module videoserver.apps.lib.video_editor
```mermaid
classDiagram
    class VideoEditorInterface {
        + get_meta()
        + edit_video()
        + capture_thumbnail()
        + capture_timeline_thumbnails()
    }

    VideoEditorInterface <|-- MoviePyVideoEditor
    class MoviePyVideoEditor {

    }

    VideoEditorInterface <|-- FFMPEGVideoEditor
    class FFMPEGVideoEditor {
        + get_meta()
        + edit_video()
        + capture_thumbnail()
        + capture_timeline_thumbnails()
        - _run_ffmpeg()
        - _get_meta()
    }
```

**Comment by huypq20110653** [comment]
# Task 3: Tổng hợp và chỉnh sửa activity diagram
## Link file tổng hợp Activity Diagram của project: https://docs.google.com/document/d/1RWGn7umSuogIBpMAyfUM7zEtKAPrk3wS564VVGUQc0g/edit?usp=sharing

**Comment by huypq20110653** [comment]
# Task 4: Tổng hợp lại các usercase, class diagram, activity diagram và xây dựng tài liệu đặc tả phần mềm hoàn chỉnh
## Link file tài liệu đặc tả phần mềm:

**Comment by huypq20110653** [comment]
# Task 5: Plan test cho chức năng create project
1. Mô tả yêu cầu chức năng: 
+ Chức năng cho phép người dùng upload video lên server và tạo một project cho video đó 
+ Video được upload phải có đuôi mở rộng trong danh sách cho phép: mov,mp4,m4a,3gp,3g2,mj2 
+ Video được upload phải đảm bảo kích thước theo yêu cầu của hệ thống 
2. Các trường hợp kiểm thử:
+ Trường hợp 1: Người dùng upload một video có đuôi mở rộng không phải là đuôi mở rộng cho phép: mov,mp4,m4a,3gp,3g2,mj2 
+ Trường hợp 2: Người dùng upload một file có đuôi mp4 nhưng không phải là video
+ Trường hợp 3: Người dùng upload một video có kích thước vượt quá kích thước cho phép của hệ thống (có thể là http-server hoặc giới hạn riêng của flask)

**Comment by huypq20110653** [comment]
# Task 6: Viết plan test cho chức năng list all project
1. Mô tả yêu cầu chức năng:
+ Chức năng cho phép người dùng xem danh sách các project có trong một trang cụ thể trên hệ thống
2. Các trường hợp kiểm thử: 
+ Trường hợp 1: Gửi request GET một trang không tồn tại/ trang không có chứa project(s) trên hệ thống
+ Trường hợp 2: Gửi request GET lấy một trang có truy vấn không đúng định dạng (số trang không phải kiểu Integer) 
+ Trường hợp 3: Gửi request GET để lấy một trang chứa project(s) có chèn malicious code/ SQL Injection đến Server
