### ISSUE TITLE
Viết plan test part 2 + viết test case

### ISSUE THREAD

**Issue by bngoc1307** [bngoc1307/Nhom04_CCPTPM#16]
- [x] Task 1: Viết plan test cho chức năng Upload Custom Image file for a preview thumbnai
- [x] Task 2: Viết plan test cho chức năng Get thumbnails file
- [x] Task 3: Viết plan test cho chức năng Get Video File
- [x] Task 4: Viết plan test cho chức năng Stream Video
- [x] Task 5: Viết test case cho chức năng List all project
- [x] Task 6: Viết test case cho chức năng Create project
- [x] Task 7: Tổng hợp các plan test và test case đồng thời xem xét chỉnh sửa

**Comment by ngvan1612** [comment]
#  Task 1: Viết plan test cho chức năng Upload Custom Image file for a preview thumbnai
Thực hiện test theo yêu cầu sau:
- Version video-server: 1.0.0
- Công cụ thực hiện kiểm thử: pyenv, circle - ci (dùng để chạy CI/CD)
- Thời gian thực hiện: 1 tuần
- Thực hiện kiểm thử các trường hợp sau:

   + Người dùng upload một file không phải hình lên nhưng đuôi file là hình
   + Người dùng upload một file hình rất lớn vượt quá kích thước cho phép của hệ thống (có thể là http-server hoặc giới hạn riêng của Flask)
   + Thực hiện upload một lượng lớn file hình lên server cùng một lúc
   + Upload 2 file lên server nhưng tên file dưới client là như nhau
   + Upload với form data rỗng lên server

**Comment by ngvan1612** [comment]
#  Task 2: Viết plan test cho chức năng Get thumbnails file
- Version video-server: 1.0.0
- Công cụ thực hiện kiểm thử: pyenv, circle - ci (dùng để chạy CI/CD)
- Thời gian thực hiện: 1 tuần
- Thực hiện kiểm thử các trường hợp sau:

    + Upload một thumbnail rồi GET (gọi là custom thumbnail)
    + Dùng thumbnail theo timeline rồi GET 
    + Upload một file không phải hình lên server rồi GET thumbnail
    + Upload một file dung lượng lớn lên rồi GET thumbnails
    + Upload liên tục 5 file hình rồi GET toàn bộ thumbnails ra

**Comment by ngvan1612** [comment]
#  Task 3: Viết plan test cho chức năng Get Video File

- Version video-server: 1.0.0
- Công cụ thực hiện kiểm thử: pyenv, circle - ci (dùng để chạy CI/CD)
- Thời gian thực hiện: 1 tuần
- Thực hiện kiểm thử các trường hợp sau:
   + Upload file lên server (tạo project) rồi download video về thử (check bằng nhau bằng hash md5)
   + Upload file lên server rồi dùng HTTP_RANGE get thử 1 đoạn đầu ra check
   + Upload file lên server (tạo project) rồi dùng HTTP_RANGE lấy một đoạn nằm ngoài khoảng video
   + Truy cập vào  url GET video nhưng trỏ project_id không tồn tại vào
   + GET liên tục vào url GET video nhưng không download (khoảng 1000 req)

**Comment by ngvan1612** [comment]
# Task 5: Viết test case cho chức năng List all project
# Task 6: Viết test case cho chức năng Create project

https://github.com/bngoc1307/Nhom04_CCPTPM

**Comment by bngoc1307** [comment]
# Task 4: Viết plan test cho chức năng Stream Video
- Version video-server: 1.0.0
- Công cụ thực hiện kiểm thử: pyenv, circle - ci (dùng để chạy CI/CD)
- Thời gian thực hiện: 1 tuần
- Thực hiện kiểm thử các trường hợp sau:
  + Upload file lên server rồi dùng HTTP_RANGE get thử 1 đoạn đầu ra check
  + Upload file lên server sau đó get từng đoạn nhỏ nối lại thử xem được video như ban đầu không?
  + Dùng HTTP-RANGE như đoạn upload lên bị lỗi hoặc quá kích thước file
  + Upload file lên server rồi GET thử 2 đoạn thời gian giống nhau và check khớp nhau
  + GET liên tục một đoạn bất kì của video và check xem chúng có hoàn toàn giống nhau không?
