### ISSUE TITLE
Viết test case cho chức năng list all project và create project

### ISSUE THREAD

**Issue by bngoc1307** [bngoc1307/Nhom04_CCPTPM#17]
- [x] Task 1: Tiếp tục triển khai viết test case list all project và thực hiện chỉnh sửa nếu cần thiết
- [x] Task 2: Tiếp tục triển khai viết test case create project và thực hiện chỉnh sửa nếu cần thiết
- [x] Task 3: Upload test case list all project lên Circle CI 
- [x] #23
- [x] Task 5: Upload test case create project lên Circle CI
- [x] #20
- [x] Task 7: Tổng hợp kết quả làm được và các lỗi của các task trên

**Comment by bngoc1307** [comment]
# Task 1. https://github.com/bngoc1307/Nhom04_CCPTPM/blob/main/test_create_project.py

**Comment by bngoc1307** [comment]
# Task 5. https://app.circleci.com/pipelines/github/bngoc1307/Nhom04_CCPTPM/100/workflows/d11d003b-0cd3-4f4c-b308-9ed8ac51dac3/jobs/100/parallel-runs/0/steps/0-104

**Comment by ngvan1612** [comment]
Task 2: Tiếp tục triển khai viết test case create project và thực hiện chỉnh sửa nếu cần thiết
[t](https://app.circleci.com/pipelines/github/bngoc1307/Nhom04_CCPTPM/107/workflows/eef9c61c-2574-4031-820c-717976d49f82/jobs/107/parallel-runs/0/steps/0-105)

**Comment by ngvan1612** [comment]
# Task 2: Tiếp tục triển khai viết test case create project và thực hiện chỉnh sửa nếu cần thiết
https://github.com/bngoc1307/Nhom04_CCPTPM/blob/main/test_list_projects.py

**Comment by ngvan1612** [comment]
# Task 7: Tổng hợp kết quả làm được và các lỗi của các task trên

- Đối với phần create-test đã thực hiện xong phần test
- Còn đối với phần list-test thì mới test được 3 trường hợp nhưng vẫn bị bị vướng khúc đợi project tạo xong rồi mới lấy thông tin được, vì hệ thống xử lý sử dụng bất đồng bộ
