### ISSUE TITLE
Viết test case cho chức năng retrieve project details và delete project

### ISSUE THREAD

**Issue by bngoc1307** [bngoc1307/Nhom04_CCPTPM#18]
- [x] Task 1: Triển khai viết test case retrieve project details
- [x] Task 2: Upload test case retrieve project lên Circle CI 
- [x] #21
- [x] Task 4: Triển khai viết test case delete project
- [x] Task 5: Upload test case delete project lên Circle CI
- [x] #22
- [x] Task 7: Tổng hợp kết quả làm được và các lỗi của các task trên

**Comment by bngoc1307** [comment]
# Task 1: #
https://github.com/bngoc1307/Nhom04_CCPTPM/blob/main/test_retrieve_project_details.py

**Comment by bngoc1307** [comment]
# Task 2: #
https://app.circleci.com/pipelines/github/bngoc1307/Nhom04_CCPTPM/100/workflows/d11d003b-0cd3-4f4c-b308-9ed8ac51dac3/jobs/100/parallel-runs/0/steps/0-106

**Comment by bngoc1307** [comment]
# Task 3: #

**Comment by bngoc1307** [comment]
# Task 4: #
https://github.com/bngoc1307/Nhom04_CCPTPM/blob/main/test_delete_project.py

**Comment by bngoc1307** [comment]
# Task 5: # 
https://app.circleci.com/pipelines/github/bngoc1307/Nhom04_CCPTPM/100/workflows/d11d003b-0cd3-4f4c-b308-9ed8ac51dac3/jobs/100/parallel-runs/0/steps/0-105

**Comment by bngoc1307** [comment]
# Task 6 : #

**Comment by bngoc1307** [comment]
# Task 7: # 
https://docs.google.com/document/d/12uACM4ZszbI1fhB5gHui79CGdBiQfQ0Gw1AQ3rrEjTw/edit?usp=sharing
