### ISSUE TITLE
Vẽ class diagram + tạo môi trường test + test activity diagram liên quan đến project

### ISSUE THREAD

**Issue by ngvan1612** [bngoc1307/Nhom04_CCPTPM#8]
- [x] Task 1. Tìm hiểu code và vẽ class diagram cho module videoserver.apps.projects.*
- [x] Task 2. Tìm hiểu code và vẽ class diagram cho module videoserver.apps.lib.storage.*
- [x] Task 3. Tìm hiểu code và vẽ class diagram cho module videoserver.apps.lib.video_editor.*
- [x] Task 4. Tìm hiểu code của các file còn lại videoserver.lib.* (trừ storage, video_editor), và videoserver.* (trừ .apps và .lib) + tổng hợp class diagram của toàn project (cho vào draw.io dẫn link qua và chụp màn hình hoặc export vào document)
- [x] Task 5. Tổ hợp các document về class diagram cho bên phần làm activity diagram làm.
- [x] #12
- [x] #13

**Comment by ngvan1612** [comment]
# Task 1. Tìm hiểu code và vẽ class diagram cho module videoserver.apps.projects.*


![Image](https://user-images.githubusercontent.com/73746704/227704639-6a75704e-1c99-46e1-915e-582dd1ef4655.png)

**Comment by ngvan1612** [comment]
# Task 2. Tìm hiểu code và vẽ class diagram cho module videoserver.apps.lib.storage.*

```mermaid
classDiagram
    class MediaStorageInterface {
        + get()
        + put()
        + replace()
        + get_range()
        + delete()
        + delete_dir()
    }

    MediaStorageInterface <|-- FileSystemStorage
    class FileSystemStorage {
        + get()
        + get_range()
        + put()
        + replace()
        + delete()
        + delete_dir()
    }
```

**Comment by ngvan1612** [comment]
#  Task 3. Tìm hiểu code và vẽ class diagram cho module videoserver.apps.lib.video_editor.*

```mermaid
classDiagram
    class VideoEditorInterface {
        + get_meta()
        + edit_video()
        + capture_thumbnail()
        + capture_timeline_thumbnails()
    }

    VideoEditorInterface <|-- MoviePyVideoEditor
    class MoviePyVideoEditor {

    }

    VideoEditorInterface <|-- FFMPEGVideoEditor
    class FFMPEGVideoEditor {
        + get_meta()
        + edit_video()
        + capture_thumbnail()
        + capture_timeline_thumbnails()
        - _run_ffmpeg()
        - _get_meta()
    }
```

**Comment by ngvan1612** [comment]
# Task 4. Tìm hiểu code của các file còn lại videoserver.lib.* (trừ storage, video_editor), và videoserver.* (trừ .apps và .lib) + tổng hợp class diagram của toàn project (cho vào draw.io dẫn link qua và chụp màn hình hoặc export vào document)

## Module videoserver.lib.logging

+ Trong module này có một hàm tên là `configure_logging` để cấu hình logging cho dự án khi chạy, input là một đường dẫn vào file log, sau đó dùng module logging của python cấu hình vào trong file đó

+ Module này cũng đặt cấu hình mặc định cho log là level INFO tức là chỉ log thông tin mức INFO, còn các mức DEBUG, TRACE trở xuống không có log ra ngoài

```python
def configure_logging(file_path):
    """
    Configure logging.

    :param file_path: file path to log config file
    :type file_path: str
    """
    if not file_path:
        return

    try:
        with open(file_path, 'r') as f:
            logging_dict = yaml.load(f, Loader=Loader)

        logging.config.dictConfig(logging_dict)
    except Exception:
        logger.warning('Cannot load logging config. File: %s', file_path)

```


## Module videoserver.lib.validator

*Module này có các hàm:*

+ create_file_name: hàm này để tạo tên file random dựa trên uuid4 (tức là guid) - tên file format bằng cách thêm random uuid sau đó là đuôi file (ext) ở trong args

```python
def create_file_name(ext):
    """
    Generates a filename using uuid4
    :param ext: file extension
    :type ext: str
    :return: generated filename
    :rtype: str
    """

    return "%s.%s" % (uuid.uuid4().hex, ext.lower())
```

+ def paginate(cursor, page): hàm này sử dụng để phân trang là chính

1. Đầu tiên lấy cấu hình mặc định là `ITEMS_PER_PAGE` ra là page_size (số lượng item trên mỗi trang)
2. Sau đó chỉnh skip lại thành page_size * (page - 1) = vị trí con trỏ đầu tiên của trang thứ page_size = tương đương `LIMIT` trong mysql
3. Sau đó cho cursor skip page_size * (page - 1) và lấy tối đa page_size item ra = tương đương với `SELECT \* FROM u LIMIT *page_size\*(page - 1)*, *page_size*`

**Comment by ngvan1612** [comment]
# Task 4. Tổ hợp các class diagram của các lớp chính của project

```mermaid
classDiagram
    class FlaskMethodView {
        + get()
        + post()
        + put()
        + delete()
        + patch()
        + __init__()
    }

    FlaskMethodView <|-- MethodView
    class MethodView {
        + __init__()
        + dispatch_request()
        + project
    }

    MethodView <|-- ListUploadProject
    class ListUploadProject {
        + post()
        + get()
    }

    MethodView <|-- RetrieveEditDestroyProject
    class RetrieveEditDestroyProject {
        + schema_edit
        + get()
        + put()
        + delete()
    }

    MethodView <|-- DuplicateProject
    class DuplicateProject {
        + post()
    }

    MethodView <|-- RetrieveOrCreateThumbnails
    class RetrieveOrCreateThumbnails {
        + schema_thumbnails
        + post()
        + get()
        + _get_timeline_thumbnails()
        + _get_preview_thumbnail()
    }

    MethodView <|-- GetRawVideo
    class GetRawVideo {
        + get()
    }

    MethodView <|-- GetRawPreviewThumbnail
    class GetRawPreviewThumbnail {
        + get()
    }

    MethodView <|-- GetRawTimelineThumbnail
    class GetRawTimelineThumbnail {
        + get()
    }
```



```mermaid
classDiagram
    class MediaStorageInterface {
        + get()
        + put()
        + replace()
        + get_range()
        + delete()
        + delete_dir()
    }

    MediaStorageInterface <|-- FileSystemStorage
    class FileSystemStorage {
        + get()
        + get_range()
        + put()
        + replace()
        + delete()
        + delete_dir()
    }
```


```mermaid
classDiagram
    class VideoEditorInterface {
        + get_meta()
        + edit_video()
        + capture_thumbnail()
        + capture_timeline_thumbnails()
    }

    VideoEditorInterface <|-- MoviePyVideoEditor
    class MoviePyVideoEditor {

    }

    VideoEditorInterface <|-- FFMPEGVideoEditor
    class FFMPEGVideoEditor {
        + get_meta()
        + edit_video()
        + capture_thumbnail()
        + capture_timeline_thumbnails()
        - _run_ffmpeg()
        - _get_meta()
    }
```
