### ISSUE TITLE
Vẽ activity diagram

### ISSUE THREAD

**Issue by ngvan1612** [bngoc1307/Nhom04_CCPTPM#9]
- [x] Task 1 Vẽ sơ đồ luồng hoạt động (activity diagram) của các lớp liên quan đến xử lý Project: create a project, list all projects, retrieve project details, delete project, duplicate project
- [x] Task 2. Vẽ sơ đồ luồng hoạt động (activity diagram) của các lớp liên quan đến xử lý Video (có sử dụng RabbitMQ): Trim, Rotate, , Scale, Crop
- [x] Task 3. Vẽ sơ đồ luồng hoạt động (activity diagram) của các lớp liên quan đến xử lý Thumbnails: capture a thumbnails for timeline, capture a thumbnail for a preview at a certain position of the video, with optional crop and rotate params, upload a custom image file for a preview thumbnail, get thumbnails files
- [x] Task 4. Vẽ sơ đồ luồng hoạt động (activity diagram) của các lớp liên quan đến xử lý Video: get video file, stream video
- [x] Task 5. Nghiên cứu luồng hoạt động của celery và viết document
- [x] Task 6. Vẽ activity diagram của các hàm liên quan đến xử lý nền dùng celery trong module videoserver.apps.project.tasks: edit_video(self, project, changes), generate_timeline_thumbnails(self, project, amount), generate_preview_thumbnail(self, project, position, crop, rotate)
- [x] Task 7. Xem xét, tổng hợp các sơ đồ activity diagram vào một file google doc duy nhất

**Comment by bngoc1307** [comment]
###Task 1:

1. List All Projects:
 

![Image](https://user-images.githubusercontent.com/126328430/227705491-d1fc61cb-c418-4b7f-8048-4681cb91599d.png)


2. Create Project:


![Image](https://user-images.githubusercontent.com/126328430/227705525-818844d1-bb3b-41a6-b846-f54a97bbd3a6.png)


3. Delete Project:


![Image](https://user-images.githubusercontent.com/126328430/227705552-3657b7fd-7319-418e-ba2e-d7033eea25f4.png)


4. Retrieve Project:


![Image](https://user-images.githubusercontent.com/126328430/227705566-6fd47f5d-6128-4196-a9d6-32f5456ee35c.png)


5. Duplicate Project:


![Image](https://user-images.githubusercontent.com/126328430/227705578-b79f261c-50fb-435b-bcee-f1b858812a03.png)

**Comment by bngoc1307** [comment]
# Task 2: # 
**_ 1.Edit video:_**


![Image](https://user-images.githubusercontent.com/126328430/227707570-4fbd94f3-e775-4b28-a079-f08e126b92fe.png)

**Comment by bngoc1307** [comment]
# Task 3 # 
**_ 1. Create thumbnail: _**


![Image](https://user-images.githubusercontent.com/126328430/227708969-3c5a3821-9649-40f7-85b6-9d4a3bae8b0c.png)

**Comment by bngoc1307** [comment]
# Task 4 # 
**_1. Get Video File: _**


![Image](https://user-images.githubusercontent.com/126328430/227711031-4ff6044b-eb72-479b-bb3a-986fd3065343.png)

**_2. Stream Video: _**


![Image](https://user-images.githubusercontent.com/126328430/227711047-705c3cbc-7fb6-4d2a-b6ce-32abf2ddb276.png)

**Comment by bngoc1307** [comment]
#Task 5: #
**_Luồng hoạt động của celery_**
1. Khởi tạo một worker Celery
2. Khởi tạo một tác vụ (task). Tác vụ này có thể là một công việc đơn giản như in ra một chuỗi hoặc phức tạp hơn là thực hiện một phép tính toán phức tạp trên dữ liệu.
3. Sau khi tác vụ được tạo ra, nó được gửi đến một trình xử lý (worker) của Celery. Trình xử lý này sẽ chạy tác vụ trong một tiến trình riêng biệt, không liên quan đến tiến trình của ứng dụng của bạn. Điều này giúp giảm thiểu tác động của tác vụ đến hiệu suất của ứng dụng
4. Trong quá trình thực thi tác vụ, trình xử lý có thể cần truy cập đến các tài nguyên khác nhau như cơ sở dữ liệu hoặc các API khác. Để làm điều này, Celery cung cấp một cơ chế cho phép truy cập đến các tài nguyên này thông qua các kết nối (connection) được quản lý bởi các bộ lưu trữ (broker). Các broker phổ biến là RabbitMQ hoặc Redis.
5. Khi tác vụ đã hoàn thành, kết quả được trả về cho ứng dụng của bạn. Nếu tác vụ không thực hiện được, Celery có thể thực hiện nhiều thao tác khác nhau để xử lý tình huống này, ví dụ như chuyển tác vụ đến một trình xử lý khác hoặc ghi nhật ký lỗi.

Tóm lại, Celery là một hệ thống quản lý tác vụ phân tán (distributed task management system) cho phép các tác vụ được thực thi trong một tiến trình riêng biệt bởi một trình xử lý. Các kết nối và bộ lưu trữ được sử dụng để truy cập đến các tài nguyên khác nhau trong quá trình thực thi tác vụ. Công cụ giám sát cho phép theo dõi hoạt động của các trình xử lý và tác vụ.

Ví dụ:
```python
# import các module cần thiết
from celery import Celery

# khởi tạo đối tượng celery
app = Celery('tasks', broker='amqp://guest@localhost//')

# định nghĩa một tác vụ bất đồng bộ
@app.task
def add(x, y):
    return x + y

# lên lịch thực hiện tác vụ bất đồng bộ
result = add.delay(4, 4)

# đợi kết quả trả về từ tác vụ bất đồng bộ
print(result.get())

```

Trong ví dụ này, chúng ta đang sử dụng Celery để tạo ra một tác vụ bất đồng bộ đơn giản (`add`) và sau đó lên lịch thực hiện nó (`result = add.delay(4, 4)`). Khi tác vụ được thực hiện, chúng ta đợi kết quả trả về bằng cách sử dụng phương thức `get()` trên đối tượng kết quả trả về từ `add.delay()`.

**Comment by bngoc1307** [comment]
#Task 7#

**Comment by bngoc1307** [comment]
# Task 7 # 
Link: [https://docs.google.com/document/d/1RWGn7umSuogIBpMAyfUM7zEtKAPrk3wS564VVGUQc0g/edit?usp=sharing]
